defmodule ContaWeb.AppComponents do
  @moduledoc """
  App-specific UI components that predate (or intentionally diverge from) the
  `phx.new` generated `ContaWeb.CoreComponents`.

  `ContaWeb.CoreComponents` is kept as an untouched copy of the scaffold generated by
  `mix phx.new` so future Phoenix upgrades can replace it wholesale. Anything the app
  needs on top of (or instead of) the scaffold defaults lives here instead, including
  `input/1`, `button/1`, and `table/1`, which are intentionally excluded from
  `ContaWeb.CoreComponents` imports (see `ContaWeb.html_helpers/0`) so these versions win.
  """
  use Phoenix.Component
  use Gettext, backend: ContaWeb.Gettext
  use ContaWeb, :verified_routes

  import ContaWeb.CoreComponents, only: [icon: 1, translate_error: 1]

  alias Phoenix.HTML.Form, as: HtmlForm
  alias Phoenix.LiveView.JS

  @doc """
  Renders the navigation elements. Nav items (`<.navbar_item>`, `<.navbar_dropdown>`)
  go in the default slot and are shown left/center-aligned; right-aligned actions
  (user menu, buttons) go in the `:actions` slot.

  ## Examples

      <.nav logo_url={~p"/images/logo.png"}>
        <.navbar_item href={~p"/dashboard"}>Dashboard</.navbar_item>
        <:actions>
          <.link href={~p"/logout"} class="btn btn-ghost btn-sm">Logout</.link>
        </:actions>
      </.nav>
  """
  attr :logo_url, :string, required: true
  attr :class, :string, default: nil
  slot :inner_block, doc: "left/center-aligned nav items"
  slot :actions, doc: "right-aligned actions (buttons, user menu)"

  def nav(assigns) do
    ~H"""
    <div class={["navbar bg-base-100 shadow-sm px-4", @class]} role="navigation" aria-label="main navigation">
      <div class="navbar-start">
        <div class="dropdown lg:hidden">
          <label tabindex="0" class="btn btn-ghost btn-circle">
            <.icon name="hero-bars-3" class="w-5 h-5" />
          </label>
          <ul
            tabindex="0"
            class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
            id="mobile-menu"
          >
            {render_slot(@inner_block)}
            {render_slot(@actions)}
          </ul>
        </div>
        <.link href={~p"/"} class="btn btn-ghost normal-case text-xl px-2">
          <img src={@logo_url} width="112" height="28" alt="Logo" />
        </.link>
      </div>

      <div :if={@inner_block != []} class="navbar-center hidden lg:flex" id="desktop-menu">
        <ul class="menu menu-horizontal px-1">
          {render_slot(@inner_block)}
        </ul>
      </div>

      <div class="navbar-end hidden lg:flex">
        {render_slot(@actions)}
      </div>
    </div>
    """
  end

  attr :href, :string, default: "#"
  slot :inner_block, required: true

  def navbar_item(assigns) do
    ~H"""
    <li>
      <a href={@href}>
        {render_slot(@inner_block)}
      </a>
    </li>
    """
  end

  attr :name, :string, required: true
  slot :inner_block, required: true

  def navbar_dropdown(assigns) do
    ~H"""
    <li class="dropdown dropdown-hover">
      <div tabindex="0" role="button" class="flex items-center gap-1">
        {@name} <.icon name="hero-chevron-down" class="w-4 h-4 ml-1" />
      </div>
      <ul tabindex="0" class="dropdown-content menu mt-0 p-2 shadow bg-base-100 rounded-box w-52 z-50">
        {render_slot(@inner_block)}
      </ul>
    </li>
    """
  end

  def navbar_divider(assigns) do
    ~H"""
    <li></li>
    """
  end

  slot :breadcrumb do
    attr :href, :string
    attr :label, :string
  end

  def breadcrumbs(assigns) do
    breadcumbs = assigns.breadcrumb

    assigns =
      assign(assigns,
        first_breadcrumbs: Enum.drop(breadcumbs, -1),
        last_breadcrumb: List.last(breadcumbs)
      )

    ~H"""
    <div class="breadcrumbs text-sm" aria-label="breadcrumbs">
      <ul>
        <li :for={breadcrumb <- @first_breadcrumbs}>
          <a href={breadcrumb.href}>{breadcrumb.label}</a>
        </li>
        <li class="text-primary font-semibold">
          <a aria-current="page" href={@last_breadcrumb.href}>{@last_breadcrumb.label}</a>
        </li>
      </ul>
    </div>
    """
  end

  slot :inner_block, required: true

  def buttons(assigns) do
    ~H"""
    <div class="flex flex-wrap gap-2">{render_slot(@inner_block)}</div>
    """
  end

  @doc """
  Renders a button.

  ## Examples

      <.button>Send!</.button>
      <.button phx-click="go" class="ml-2">Send!</.button>
  """
  attr :class, :string, default: ""
  attr :rest, :global, include: ~w(disabled form name value type)
  slot :inner_block, required: true

  def button(assigns) do
    ~H"""
    <button class={["btn", @class]} {@rest}>{render_slot(@inner_block)}</button>
    """
  end

  @doc """
  Renders a modal.

  ## Examples

      <.modal id="confirm-modal">
        This is a modal.
      </.modal>

  JS commands may be passed to the `:on_cancel` to configure
  the closing/cancel event, for example:

      <.modal id="confirm" on_cancel={JS.navigate(~p"/posts")}>
        This is another modal.
      </.modal>

  """
  attr :id, :string, required: true
  attr :show, :boolean, default: false
  attr :on_cancel, JS, default: %JS{}
  slot :inner_block, required: true

  def modal(assigns) do
    ~H"""
    <div
      id={@id}
      phx-mounted={@show && show_modal(@id)}
      phx-remove={hide_modal(@id)}
      data-cancel={JS.exec(@on_cancel, "phx-remove")}
      class="modal"
    >
      <div class="modal-box" role="dialog" aria-modal="true" tabindex="0">
        <.focus_wrap
          id={"#{@id}-container"}
          phx-window-keydown={JS.exec("data-cancel", to: "##{@id}")}
          phx-key="escape"
          phx-click-away={JS.exec("data-cancel", to: "##{@id}")}
        >
          {render_slot(@inner_block)}
        </.focus_wrap>
      </div>
      <div
        id={"#{@id}-bg"}
        class="modal-backdrop"
        aria-hidden="true"
        phx-click={JS.exec("data-cancel", to: "##{@id}")}
      />
    </div>
    """
  end

  @doc """
  Renders a simple form.

  ## Examples

      <.simple_form for={@form} phx-change="validate" phx-submit="save">
        <.input field={@form[:email]} label="Email"/>
        <.input field={@form[:username]} label="Username" />
        <:actions>
          <.button>Save</.button>
        </:actions>
      </.simple_form>
  """
  attr :for, :any, required: true, doc: "the datastructure for the form"
  attr :as, :any, default: nil, doc: "the server side parameter to collect all input under"

  attr :rest, :global,
    include: ~w(autocomplete name rel action enctype method novalidate target multipart),
    doc: "the arbitrary HTML attributes to apply to the form tag"

  slot :inner_block, required: true

  slot :actions, doc: "the slot for form actions, such as a submit button"

  def simple_form(assigns) do
    ~H"""
    <.form :let={f} for={@for} as={@as} {@rest}>
      {render_slot(@inner_block, f)}
      <div :for={action <- @actions}>
        {render_slot(action, f)}
      </div>
    </.form>
    """
  end

  attr :for, :any, required: true, doc: "the datastructure for the form"
  attr :as, :any, default: nil, doc: "the server side parameter to collect all input under"

  attr :rest, :global,
    include: ~w(autocomplete name rel action enctype method novalidate target multipart),
    doc: "the arbitrary HTML attributes to apply to the form tag"

  slot :inner_block, required: true
  slot :actions, doc: "the slot for form actions, such as a submit button"

  def modal_form(assigns) do
    ~H"""
    <div class="modal modal-open">
      <div class="modal-backdrop bg-base-300 bg-opacity-50"></div>
      <div class="modal-box px-0 pb-0 shadow-xl overflow-hidden">
        <header class="px-6 py-4 bg-base-200 border-b border-base-300">
          <h3 class="font-bold text-lg">{@title}</h3>
        </header>
        <section class="px-6 py-4">
          <.simple_form for={@for} as={@as} {@rest}>
            {render_slot(@inner_block)}
          </.simple_form>
        </section>
        <footer class="px-6 py-4 bg-base-200 border-t border-base-300 flex justify-end gap-2">
          {render_slot(@actions)}
        </footer>
      </div>
    </div>
    """
  end

  @doc """
  Renders an input with label and error messages.

  A `Phoenix.HTML.FormField` may be passed as argument,
  which is used to retrieve the input name, id, and values.
  Otherwise all attributes may be passed explicitly.

  ## Types

  This function accepts all HTML input types, considering that:

    * You may also set `type="select"` to render a `<select>` tag

    * `type="checkbox"` is used exclusively to render boolean values

    * For live file uploads, see `Phoenix.Component.live_file_input/1`

  See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
  for more information.

  ## Examples

      <.input field={@form[:email]} type="email" />
      <.input name="my-input" errors={["oh no!"]} />
  """
  attr :field, Phoenix.HTML.FormField,
    doc: "a form field struct retrieved from the form, for example: @form[:email]"

  attr :id, :string, default: nil
  attr :name, :any
  attr :label, :string, default: nil
  attr :value, :any
  attr :type, :string, default: "text"
  attr :prompt, :string, default: nil
  attr :options, :list, default: []
  attr :multiple, :boolean, default: false
  attr :checked, :boolean
  attr :control_label, :string, default: nil
  attr :class, :string, default: nil
  attr :input_class, :string, default: nil
  attr :errors, :list, default: []
  attr :offset, :boolean, default: true

  attr :rest, :global,
    include: ~w(accept autocomplete capture cols disabled form list max maxlength min minlength
                pattern placeholder readonly required rows size step upload files)

  slot :inner_block

  def input(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
    assigns
    |> assign(field: nil, id: assigns[:id] || field.id)
    |> assign(:errors, Enum.map(field.errors, &translate_error(&1)))
    |> assign_new(:name, fn -> if assigns[:multiple], do: field.name <> "[]", else: field.name end)
    |> assign_new(:value, fn -> field.value end)
    |> input()
  end

  def input(%{type: "checkbox"} = assigns) do
    assigns =
      assign_new(assigns, :checked, fn ->
        HtmlForm.normalize_value("checkbox", assigns[:value])
      end)

    ~H"""
    <.field id={@id} name={@name} label={@label} class={@class} offset={@offset} errors={@errors}>
      <label class="label cursor-pointer justify-start gap-3 mt-2">
        <input type="hidden" name={@name} value="false" />
        <input
          type="checkbox"
          id={@id}
          name={@name}
          value="true"
          checked={@checked}
          class={["checkbox checkbox-primary", @errors != [] && "checkbox-error"]}
          {@rest}
        />
        <span class="label-text">{@control_label}</span>
      </label>
    </.field>
    """
  end

  def input(%{type: "select"} = assigns) do
    ~H"""
    <.field id={@id} name={@name} label={@label} class={@class} offset={@offset} errors={@errors}>
      <select
        id={@id}
        name={@name}
        multiple={@multiple}
        class={[
          "select select-bordered",
          !((@input_class || "") =~ ~r/\bw-/) && "w-full",
          @errors != [] && "select-error",
          @input_class
        ]}
        {@rest}
      >
        <option :if={@prompt} value="">{@prompt}</option>
        {Phoenix.HTML.Form.options_for_select(@options, @value)}
      </select>
    </.field>
    """
  end

  def input(%{type: "textarea"} = assigns) do
    ~H"""
    <.field id={@id} name={@name} label={@label} class={@class} offset={@offset} errors={@errors}>
      <textarea
        id={@id}
        name={@name}
        class={["textarea textarea-bordered w-full", @errors != [] && "textarea-error"]}
        {@rest}
      ><%= Phoenix.HTML.Form.normalize_value("textarea", @value) %></textarea>
    </.field>
    """
  end

  def input(%{type: "file"} = assigns) do
    ~H"""
    <.field id={@id} name={@name} label={@label} class={@class} offset={@offset} errors={@errors}>
      <div class="flex flex-wrap gap-2 mb-2">
        <span :if={length(@rest.files) == 0 and length(@rest.upload.entries) == 0} class="text-sm opacity-60">
          {gettext("There are no attachments")}
        </span>
        <div :for={file <- @rest.files} class="badge badge-success gap-2 py-3 px-3">
          {file["name"]}
          <button
            type="button"
            class="btn btn-ghost btn-xs btn-circle"
            phx-click="remove"
            phx-target={@rest."phx-target"}
            phx-value-id={file["id"]}
            data={[confirm: gettext("Are you sure?")]}
          >
            <.icon name="hero-x-mark" class="w-3 h-3" />
          </button>
        </div>
        <div :for={entry <- @rest.upload.entries} class="badge badge-primary gap-2 py-3 px-3">
          {entry.client_name}
          <button
            type="button"
            class="btn btn-ghost btn-xs btn-circle"
            phx-click="remove"
            phx-target={@rest."phx-target"}
            phx-value-ref={entry.ref}
            data={[confirm: gettext("Are you sure?")]}
          >
            <.icon name="hero-x-mark" class="w-3 h-3" />
          </button>
        </div>
      </div>
      <.live_file_input upload={@rest.upload} class="file-input file-input-bordered file-input-primary w-full" />
    </.field>
    """
  end

  def input(%{type: "static"} = assigns) do
    ~H"""
    <.field label={@label} class={@class} offset={@offset}>
      <input
        type="text"
        value={Phoenix.HTML.Form.normalize_value("text", @value)}
        class="input input-ghost w-full"
        readonly
        {@rest}
      />
    </.field>
    """
  end

  def input(%{type: "hidden"} = assigns) do
    ~H"""
    <input type="hidden" name={@name} value={Phoenix.HTML.Form.normalize_value("text", @value)} {@rest} />
    """
  end

  def input(assigns) do
    ~H"""
    <.field id={@id} name={@name} label={@label} class={@class} offset={@offset} errors={@errors}>
      <input
        type={@type}
        name={@name}
        id={@id}
        value={Phoenix.HTML.Form.normalize_value(@type, @value)}
        class={[
          "input input-bordered",
          !((@input_class || "") =~ ~r/\bw-/) && "w-full",
          @errors != [] && "input-error",
          @input_class
        ]}
        {@rest}
      />
    </.field>
    """
  end

  attr :id, :string, default: nil
  attr :name, :any, default: nil
  attr :label, :string, default: nil
  attr :class, :string, default: nil
  attr :errors, :list, default: []
  attr :offset, :boolean, default: true
  slot :inner_block, required: true

  def field(assigns) do
    assigns =
      Map.merge(
        %{
          id: nil,
          name: nil,
          label: nil,
          class: nil,
          errors: [],
          offset: true
        },
        assigns
      )

    ~H"""
    <div class={[
      "form-control",
      !((@class || "") =~ ~r/\bw-/) && "w-full",
      @class,
      @offset && "mb-4"
    ]}>
      <div :if={@label} class="label">
        <.label for={@id} class="label-text font-semibold">{@label}</.label>
      </div>
      <div class="mt-1 relative" phx-feedback-for={@name}>
        {render_slot(@inner_block)}
      </div>
      <.error :for={msg <- @errors}>{msg}</.error>
    </div>
    """
  end

  attr :input_class, :string, default: ""
  attr :button_class, :string, default: "is-info"
  attr :label, :string
  attr :name, :string, default: "search"
  attr :value, :string
  attr :debounce, :integer, default: 1_000

  def search(assigns) do
    ~H"""
    <form role="search" phx-change="search">
      <div class="join w-full">
        <input
          class={["input input-bordered join-item w-full", @input_class]}
          type="search"
          placeholder={@label}
          name={@name}
          value={@value}
          phx-debounce={@debounce}
          autocomplete="off"
          autocorrect="off"
          autocapitalize="off"
          enterkeyhint="search"
          spellcheck="false"
          phx-key="Enter"
        />
      </div>
    </form>
    """
  end

  @doc """
  Renders a label.
  """
  attr :for, :string, default: nil
  attr :class, :string, default: nil
  slot :inner_block, required: true

  def label(assigns) do
    ~H"""
    <label for={@for} class={["label", @class]}>
      {render_slot(@inner_block)}
    </label>
    """
  end

  @doc """
  Generates a generic error message.
  """
  slot :inner_block, required: true

  def error(assigns) do
    ~H"""
    <p class="mt-2 text-sm text-error flex items-center gap-2">
      <.icon name="hero-exclamation-triangle" class="w-4 h-4" /> {render_slot(@inner_block)}
    </p>
    """
  end

  @doc ~S"""
  Renders a table with generic styling.

  ## Examples

      <.table id="users" rows={@users}>
        <:col :let={user} label="id"><%= user.id %></:col>
        <:col :let={user} label="username"><%= user.username %></:col>
      </.table>
  """
  attr :id, :string, required: true
  attr :rows, :list, required: true
  attr :row_id, :any, default: nil, doc: "the function for generating the row id"
  attr :row_click, :any, default: nil, doc: "the function for handling phx-click on each row"

  attr :row_item, :any,
    default: &Function.identity/1,
    doc: "the function for mapping each row before calling the :col and :action slots"

  slot :col, required: true do
    attr :class, :string
    attr :label, :string
  end

  slot :action, doc: "the slot for showing user actions in the last table column"

  def table(assigns) do
    assigns =
      with %{rows: %Phoenix.LiveView.LiveStream{}} <- assigns do
        assign(assigns, row_id: assigns.row_id || fn {id, _item} -> id end)
      end

    ~H"""
    <div class="overflow-x-auto">
      <table class="table table-zebra hover w-full">
        <thead>
          <tr>
            <th :for={col <- @col}>{col[:label]}</th>
            <th :if={@action != []}>
              <span class="sr-only">{gettext("Actions")}</span>
            </th>
          </tr>
        </thead>
        <tbody
          id={@id}
          phx-update={if is_struct(@rows, Phoenix.LiveView.LiveStream), do: "stream"}
          phx-viewport-bottom="next-page"
        >
          <tr :for={{id, %_{}} = row <- @rows} id={id}>
            <td :for={col <- @col} class={col[:class]}>
              {render_slot(col, @row_item.(row))}
            </td>
            <td :if={@action != []} class="text-right whitespace-nowrap">
              <%= for action <- @action do %>
                {render_slot(action, @row_item.(row))}
              <% end %>
            </td>
          </tr>
          <tr :for={{id, %{title: title, row: row}} <- @rows} id={id} class="bg-base-200">
            <th :if={is_nil(row)} colspan={length(@col) + if(@action != [], do: 1, else: 0)} class="font-bold">
              {title}
            </th>
            <td :for={col <- @col} :if={is_nil(title)} class={col[:class]}>
              {render_slot(col, @row_item.({row.id, row}))}
            </td>
            <td :if={@action != [] and is_nil(title)} class="text-right whitespace-nowrap">
              <%= for action <- @action do %>
                {render_slot(action, @row_item.({row.id, row}))}
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    """
  end

  @doc ~S"""
  Renders a very simple table with generic styling.

  ## Examples

      <.simple_table id="users" rows={@users}>
        <:col :let={user} label="id"><%= user.id %></:col>
        <:col :let={user} label="username"><%= user.username %></:col>
      </.simple_table>
  """
  attr :id, :string, required: true
  attr :rows, :list, required: true

  slot :col, required: true do
    attr :class, :string
    attr :label, :string
  end

  def simple_table(assigns) do
    ~H"""
    <div class="overflow-x-auto">
      <table class="table table-zebra hover w-full">
        <thead>
          <tr>
            <th :for={col <- @col}>{col[:label]}</th>
          </tr>
        </thead>
        <tr :for={row <- @rows} id={row.id}>
          <td :for={col <- @col} class={col[:class]}>
            {render_slot(col, row)}
          </td>
        </tr>
      </table>
    </div>
    """
  end

  @doc """
  Renders a back navigation link.

  ## Examples

      <.back navigate={~p"/posts"}>Back to posts</.back>
  """
  attr :navigate, :any, required: true
  slot :inner_block, required: true

  def back(assigns) do
    ~H"""
    <div class="mt-4">
      <.link navigate={@navigate} class="btn btn-ghost btn-sm gap-2">
        <.icon name="hero-arrow-left" class="w-4 h-4" /> {render_slot(@inner_block)}
      </.link>
    </div>
    """
  end

  ## JS Commands

  def show_modal(js \\ %JS{}, id) when is_binary(id) do
    js
    |> JS.add_class("modal-open", to: "##{id}")
    |> JS.focus_first(to: "##{id}-container")
  end

  def hide_modal(js \\ %JS{}, id) do
    js
    |> JS.remove_class("modal-open", to: "##{id}")
    |> JS.pop_focus()
  end
end
